### PR TITLE
chore/refactor-build-process

### PR DESCRIPTION
**Pull request by eliasm307**

### CODE REVIEW

**Comment by baoshan** [comment]
Hi, @eliasm307,

Thanks for improving the building & publishing process! 0.12.1 works for me but not 0.12.2:

```
Module not found: Can't resolve '../locales'
```

I guess we need to change this line?

https://github.com/eliasm307/monaco-editor-typescript-locales/blob/1a57e940d10e922e689153d957ea918874ae46b8/packages/monaco-util/src/index.ts#L329

Also, can you enlighten me how to perform a local build? `npm run ci:publish` doesn’t work for me 🤷‍♂️ :

```
baoshan@Baoshans-MBP monaco-editor-typescript-locales % npm run ci:publish

> ci:publish
> npm run --prefix packages/monaco-util run publish:minor

npm ERR! Missing script: "run"
npm ERR! 
npm ERR! To see a list of scripts, run:
npm ERR!   npm run
```

Let me know if you prefer a PR. Thanks!

**Comment by eliasm307** [comment]
Oops yes you're right, I'll look into this tonight. Can you use 0.12.1 for now, I need add the integration tests to the publish process so this gets caught

Also for running the publish script you have an extra "run", it should be

```
npm --prefix packages/monaco-util run publish:minor
```

**Comment by eliasm307** [comment]
Ah I see the mistake was in my changes 😅

**Comment by eliasm307** [comment]
@baoshan I've published 0.12.3, let me know if there are still issues with this one

**Comment by baoshan** [comment]
It works like a charm 👍

**Comment by eliasm307** [comment]
Great! Thanks for your feedback and quick responses 🙂

**Pull request merged**
